### ISSUE TITLE
全部挖矿节点启动轻节点服务后无法出块

### ISSUE THREAD

**Issue by xiaowenwe** [elastos/Elastos.ELA.SideChain.ETH#2]
./geth  --lightserv 25   --mine   所有挖矿节点启动轻节点服务后无法出块

**Comment by ttblack** [comment]
是这样的。因为以太坊会优先连接light服务节点。但light服务节点没有annouce这个消息。所以会报错。连不上。

**Comment by ttblack** [comment]
所以不能全部开启轻节点服务
