### ISSUE TITLE
Transaction with 256bit payload will be pending forever

### ISSUE THREAD

**Issue by luckyyang** [elastos/Elastos.ELA.SideChain.ETH#75]
#### Expected behaviour
Transaction with 256bit payload send successfully

#### Actual behaviour
pending forever

#### Steps to reproduce the behaviour

```
> var txn3=web3.eth.sendTransaction({from:pubkey,to:pubkey,value:0,data:"0x18f487671496449f2bfb9f5c9c6524827d3889b4eaa62b3a8bc4572a2e7794eb"})
undefined
> txn3
"0xc78703a1694756f49eda26988d2d0037205f486d97b2b34d79bb6adbe1ee744a"
> web3.eth.getTransaction(txn3)
{
  blockHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  blockNumber: null,
  from: "0x039470b1016ada0822914ed44eba4756aee90cbf",
  gas: 90000,
  gasPrice: 1000000000,
  hash: "0xc78703a1694756f49eda26988d2d0037205f486d97b2b34d79bb6adbe1ee744a",
  input: "0x18f487671496449f2bfb9f5c9c6524827d3889b4eaa62b3a8bc4572a2e7794eb",
  nonce: 5,
  r: "0x72b0290e145bd1aafa2614a1d2712bc95c86b792fb67e8172a156057e32579f9",
  s: "0xd71269efcd19282b61c210583816665d699fa55f106365d9552f35a51970810",
  to: "0x039470b1016ada0822914ed44eba4756aee90cbf",
  transactionIndex: 0,
  v: "0x25",
  value: 0
}
> web3.eth.getTransaction(txn3)
{
  blockHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  blockNumber: null,
  from: "0x039470b1016ada0822914ed44eba4756aee90cbf",
  gas: 90000,
  gasPrice: 1000000000,
  hash: "0xc78703a1694756f49eda26988d2d0037205f486d97b2b34d79bb6adbe1ee744a",
  input: "0x18f487671496449f2bfb9f5c9c6524827d3889b4eaa62b3a8bc4572a2e7794eb",
  nonce: 5,
  r: "0x72b0290e145bd1aafa2614a1d2712bc95c86b792fb67e8172a156057e32579f9",
  s: "0xd71269efcd19282b61c210583816665d699fa55f106365d9552f35a51970810",
  to: "0x039470b1016ada0822914ed44eba4756aee90cbf",
  transactionIndex: 0,
  v: "0x25",
  value: 0
}
> web3.eth.getTransaction(txn3)
{
  blockHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  blockNumber: null,
  from: "0x039470b1016ada0822914ed44eba4756aee90cbf",
  gas: 90000,
  gasPrice: 1000000000,
  hash: "0xc78703a1694756f49eda26988d2d0037205f486d97b2b34d79bb6adbe1ee744a",
  input: "0x18f487671496449f2bfb9f5c9c6524827d3889b4eaa62b3a8bc4572a2e7794eb",
  nonce: 5,
  r: "0x72b0290e145bd1aafa2614a1d2712bc95c86b792fb67e8172a156057e32579f9",
  s: "0xd71269efcd19282b61c210583816665d699fa55f106365d9552f35a51970810",
  to: "0x039470b1016ada0822914ed44eba4756aee90cbf",
  transactionIndex: 0,
  v: "0x25",
  value: 0
}
> eth.pendingTransactions
[{
    blockHash: null,
    blockNumber: null,
    from: "0x039470b1016ada0822914ed44eba4756aee90cbf",
    gas: 90000,
    gasPrice: 1000000000,
    hash: "0xc78703a1694756f49eda26988d2d0037205f486d97b2b34d79bb6adbe1ee744a",
    input: "0x18f487671496449f2bfb9f5c9c6524827d3889b4eaa62b3a8bc4572a2e7794eb",
    nonce: 5,
    r: "0x72b0290e145bd1aafa2614a1d2712bc95c86b792fb67e8172a156057e32579f9",
    s: "0xd71269efcd19282b61c210583816665d699fa55f106365d9552f35a51970810",
    to: "0x039470b1016ada0822914ed44eba4756aee90cbf",
    transactionIndex: 0,
    v: "0x25",
    value: 0
}]
```

**Comment by luckyyang** [comment]
This issue is reported by Guy, CTO of ProvenDB

**Comment by luckyyang** [comment]
Any update?

**Comment by ttblack** [comment]
> privkey="138E206ACD772F221417F526E93FFD780A79D1B280632B1AA70EFF886E07F984"
"138E206ACD772F221417F526E93FFD780A79D1B280632B1AA70EFF886E07F984"
>
> pubkey="0x039470B1016ADA0822914eD44eBa4756AEe90cbF"
"0x039470B1016ADA0822914eD44eBa4756AEe90cbF"
> personal.importRawKey(privkey,"password")
"0x039470b1016ada0822914ed44eba4756aee90cbf"
> personal.unlockAccount(pubkey,"password",15000)
true
> eth.getBalance(pubkey)
49933464000000000
> txn=web3.eth.sendTransaction({from:pubkey,to:pubkey,value:0})
"0x42cb6ac99c52e82ca00ed9a45fc6fa820c3a711fa4a1e2a10b5a9d315c379b36"
> eth.getTransaction("0xc3ceaef51961ad8f4c61c8457cc1a358fdb6e31ec4e41f8b75f67800a3380b48")
null
> eth.getTransaction("0x42cb6ac99c52e82ca00ed9a45fc6fa820c3a711fa4a1e2a10b5a9d315c379b36")
{
  blockHash: "0x607141272e67fed539ab27c08d47a5fcc039f2b15859455f87ea5e0941a1ad9e",
  blockNumber: 1252991,
  from: "0x039470b1016ada0822914ed44eba4756aee90cbf",
  gas: 90000,
  gasPrice: 1000000000,
  hash: "0x42cb6ac99c52e82ca00ed9a45fc6fa820c3a711fa4a1e2a10b5a9d315c379b36",
  input: "0x",
  nonce: 3,
  r: "0x1b112f98bcec2bd3a71d183b01e3467d03ed8adc1aadf4d787408f408f2bc226",
  s: "0x6023a2b1d9fda155f7d5bcd17086e9077a9e004377a266c08092d302624aa567",
  to: "0x039470b1016ada0822914ed44eba4756aee90cbf",
  transactionIndex: 0,
  v: "0x2a",
  value: 0
}
> txn2=web3.eth.sendTransaction({from:pubkey,to:pubkey,value:0,data:"0x039470B1016ADA0822914eD44eBa4756AEe90cbF"})

"0x7646735c1dd1cce9fc002c117d615fa7fe2be9ea0087651fd30b240f8792eebd"
> eth.getTransactionReceipt(txn2)
{
  blockHash: "0xadafc9a849fc19853c9f150ff349e3a67ef4cbe9ad3f142aa4c160dcda08f1ea",
  blockNumber: 1252996,
  contractAddress: null,
  cumulativeGasUsed: 22360,
  from: "0x039470b1016ada0822914ed44eba4756aee90cbf",
  gasUsed: 22360,
  logs: [],
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  status: "0x1",
  to: "0x039470b1016ada0822914ed44eba4756aee90cbf",
  transactionHash: "0x7646735c1dd1cce9fc002c117d615fa7fe2be9ea0087651fd30b240f8792eebd",
  transactionIndex: 0
}
> txn3=web3.eth.sendTransaction({from:pubkey,to:pubkey,value:0,data:"0x18f487671496449f2bfb9f5c9c6524827d3889b4eaa62b3a8bc4572a2e7794eb"})
"0xd16d9c9db5aea645e6da2fb002a7d0e18496ca903b624e9fe1ba474af14e9a18"
> eth.getTransaction(txn3)
{
  blockHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  blockNumber: null,
  from: "0x039470b1016ada0822914ed44eba4756aee90cbf",
  gas: 90000,
  gasPrice: 1000000000,
  hash: "0xd16d9c9db5aea645e6da2fb002a7d0e18496ca903b624e9fe1ba474af14e9a18",
  input: "0x18f487671496449f2bfb9f5c9c6524827d3889b4eaa62b3a8bc4572a2e7794eb",
  nonce: 5,
  r: "0x867fd9a7050e48da80d2df300ad967ba8e8631faba3667653a5ab6d26b144187",
  s: "0x30bb089726406781b725f0064ee9ca28d18ec85c19ea5ffc39605cd871b85a07",
  to: "0x039470b1016ada0822914ed44eba4756aee90cbf",
  transactionIndex: 0,
  v: "0x29",
  value: 0
}
> eth.getTransaction(txn3)
{
  blockHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  blockNumber: null,
  from: "0x039470b1016ada0822914ed44eba4756aee90cbf",
  gas: 90000,
  gasPrice: 1000000000,
  hash: "0xd16d9c9db5aea645e6da2fb002a7d0e18496ca903b624e9fe1ba474af14e9a18",
  input: "0x18f487671496449f2bfb9f5c9c6524827d3889b4eaa62b3a8bc4572a2e7794eb",
  nonce: 5,
  r: "0x867fd9a7050e48da80d2df300ad967ba8e8631faba3667653a5ab6d26b144187",
  s: "0x30bb089726406781b725f0064ee9ca28d18ec85c19ea5ffc39605cd871b85a07",
  to: "0x039470b1016ada0822914ed44eba4756aee90cbf",
  transactionIndex: 0,
  v: "0x29",
  value: 0
}
> eth.getTransaction(txn3)
{
  blockHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  blockNumber: null,
  from: "0x039470b1016ada0822914ed44eba4756aee90cbf",
  gas: 90000,
  gasPrice: 1000000000,
  hash: "0xd16d9c9db5aea645e6da2fb002a7d0e18496ca903b624e9fe1ba474af14e9a18",
  input: "0x18f487671496449f2bfb9f5c9c6524827d3889b4eaa62b3a8bc4572a2e7794eb",
  nonce: 5,
  r: "0x867fd9a7050e48da80d2df300ad967ba8e8631faba3667653a5ab6d26b144187",
  s: "0x30bb089726406781b725f0064ee9ca28d18ec85c19ea5ffc39605cd871b85a07",
  to: "0x039470b1016ada0822914ed44eba4756aee90cbf",
  transactionIndex: 0,
  v: "0x29",
  value: 0
}
> eth.pendingTransactions
[{
    blockHash: null,
    blockNumber: null,
    from: "0x039470b1016ada0822914ed44eba4756aee90cbf",
    gas: 90000,
    gasPrice: 1000000000,
    hash: "0xd16d9c9db5aea645e6da2fb002a7d0e18496ca903b624e9fe1ba474af14e9a18",
    input: "0x18f487671496449f2bfb9f5c9c6524827d3889b4eaa62b3a8bc4572a2e7794eb",
    nonce: 5,
    r: "0x867fd9a7050e48da80d2df300ad967ba8e8631faba3667653a5ab6d26b144187",
    s: "0x30bb089726406781b725f0064ee9ca28d18ec85c19ea5ffc39605cd871b85a07",
    to: "0x039470b1016ada0822914ed44eba4756aee90cbf",
    transactionIndex: 0,
    v: "0x29",
    value: 0
}]
> eth.pendingTransactions
[{
    blockHash: null,
    blockNumber: null,
    from: "0x039470b1016ada0822914ed44eba4756aee90cbf",
    gas: 90000,
    gasPrice: 1000000000,
    hash: "0xd16d9c9db5aea645e6da2fb002a7d0e18496ca903b624e9fe1ba474af14e9a18",
    input: "0x18f487671496449f2bfb9f5c9c6524827d3889b4eaa62b3a8bc4572a2e7794eb",
    nonce: 5,
    r: "0x867fd9a7050e48da80d2df300ad967ba8e8631faba3667653a5ab6d26b144187",
    s: "0x30bb089726406781b725f0064ee9ca28d18ec85c19ea5ffc39605cd871b85a07",
    to: "0x039470b1016ada0822914ed44eba4756aee90cbf",
    transactionIndex: 0,
    v: "0x29",
    value: 0
}]
> eth.pendingTransactions
[{
    blockHash: null,
    blockNumber: null,
    from: "0x039470b1016ada0822914ed44eba4756aee90cbf",
    gas: 90000,
    gasPrice: 1000000000,
    hash: "0xd16d9c9db5aea645e6da2fb002a7d0e18496ca903b624e9fe1ba474af14e9a18",
    input: "0x18f487671496449f2bfb9f5c9c6524827d3889b4eaa62b3a8bc4572a2e7794eb",
    nonce: 5,
    r: "0x867fd9a7050e48da80d2df300ad967ba8e8631faba3667653a5ab6d26b144187",
    s: "0x30bb089726406781b725f0064ee9ca28d18ec85c19ea5ffc39605cd871b85a07",
    to: "0x039470b1016ada0822914ed44eba4756aee90cbf",
    transactionIndex: 0,
    v: "0x29",
    value: 0
}]
> eth.pendingTransactions
[]
>

**Comment by ttblack** [comment]
需要第一个区块多个确认。需要等一段时间。

**Comment by ClarenceL** [comment]
I was unable to reproduce, maybe it's intermittent?

**Comment by ttblack** [comment]
经过测试。如果用本地节点同步testnet的数据。然后发送携带256字节的数据。会成功打包。
如果使用https://rpc.elaeth.io 这个网站发送会失败。所以初步认为是https://rpc.elaeth.io 这个网站可能有问题。

**Comment by ttblack** [comment]
是release_v0.0.2有问题，会在最新的版本上进行修正。请等待升级更新。
